import employeeImage from '../../assets/images/pic.jpg';

export const employee = [
  {
    id: 1,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'software engineering',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 2,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'data engineering',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 3,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'data ',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 4,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'web scraping',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 5,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'frontend engineering',
    phonenumber: '(+234)(0)8103248902',
  },
  {
    id: 6,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'backend engineering',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 7,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'product designer',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 8,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'developer advocate',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 9,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'lead engineer',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
  {
    id: 10,
    img: employeeImage,
    name: 'dimeji johnson',
    job: 'ui/ux',
    phonenumber: '(+234)(0)8103248902',
    email: 'dimeji@samasys.tech',
  },
];
